server:
  port: 3000
  servlet:
    context-path: /

# MySQL和Redis配置
spring:
  data:
    redis:
      database: 0
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1
        host: ******
      password: ******
  datasource:
    url: jdbc:mysql:///codearena
    username: root
    password: ******
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

# mybatis-plus的配置
mybatis-plus:
  type-aliases-package: com.xty.backend
  global-config:
    db-config:
      #      logic-delete-field: isDeleted  #全局逻辑删除
      id-type: auto #主键策略自增长
