server:
  port: 3000
  servlet:
    context-path: /

# 连接池配置和时间配置
spring:
  datasource:
    url: jdbc:mysql:///kob
    username: root
    password: xty510521
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

# mybatis-plus的配置
mybatis-plus:
  type-aliases-package: com.xty.backend
  global-config:
    db-config:
#      logic-delete-field: isDeleted  #全局逻辑删除
      id-type: auto #主键策略自增长